SECRET_KEY = ""

MAX_FIELD_LENGTH = 255
MAX_USERNAME_LENGTH = 150
MAX_EMAIL_LENGTH = 150

MAX_SLUG_LENGTH = 50
MIN_SLUG_LENGTH = 1

SECRET_KEY = "hhz7l-ltdismtf@bzyz+rple7*s*w$jak%whj@(@u0eok^f9k4"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 120
