"""update2 review

Revision ID: 405277e3d35b
Revises: 989d51c27d76
Create Date: 2024-05-18 15:18:08.910803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405277e3d35b'
down_revision: Union[str, None] = '989d51c27d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'score')
    # ### end Alembic commands ###
