"""update user

Revision ID: df73162f5772
Revises: 3dc2e29f4257
Create Date: 2024-05-18 14:28:20.820680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df73162f5772'
down_revision: Union[str, None] = '3dc2e29f4257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmation_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmation_code')
    # ### end Alembic commands ###
